### ISSUE TITLE
bosh mode

### ISSUE THREAD

**Issue by timbergeron** [quakeone/CRx#29]

**Comment by inf1niti** [comment]
I would actually not mind brainstorming if there are ways to make this mode better.

The idea is you have 999 health and 999 red armor?  Am I missing anything?

**Comment by timbergeron** [comment]
Is he thinking a povdmm for 1 on 1 so the players start with the same and then one dies?

**Comment by buckshot41** [comment]
I believe this has been replaced with prewar in match mode

**Comment by timbergeron** [comment]
And or dmm4

--
Tim Bergeron
timbergeron.com
