### ISSUE TITLE
Mod switch from dm to ctf goes to a default map

### ISSUE THREAD

**Issue by timbergeron** [quakeone/CRx#34]
Mod switch from dm to ctf goes to a default DM map and a default CTF map. DM-> dm3, ctf-> ctf1

**Comment by sputnikutah** [comment]
This is annoying a heck when testing; ca flips to dm3 ctf flips to ctf1. This is also the reason back in feb2022 the warp menu was considered broken
"the only thing about this, is that there are currently paths of annoyance.
I don't think the solution is to make people use the advanced combos though, but to fix the annoyance.
for example: 
I'm playing dm, and I want to play CTF.  I change to a ctf2m3 map but I forgot to change the mode, so I type 'ctf' and I get warped to ctf1.
in "happy path" cases, the warp to a default map is a benefit.  But in different scenarios it adds friction. (edited)
"
if the map parameter wasnt set then it shouldnt pick a default map; it is implied we want to stay on the current map.
