### ISSUE TITLE
mouse click to switch between fly / eyecam when observer

### ISSUE THREAD

**Issue by timbergeron** [quakeone/CRx#52]

**Comment by sputnikutah** [comment]
holding mouse1 allows for freelooking in chasecam, holding mouse1 in flymode allows you to pass thru walls..
oh maybe use mouse2 to cycle thru modes?

**Comment by timbergeron** [comment]
Can you just move around the map and clip through walls without having to press a button? And then mouse1 is for the toggles. This it the KTX behavior.
